default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: paras_development

test:
  <<: *default
  database: paras_test

production:
  url: <%= "#{ENV['DATABASE_URL']}?sslmode=require" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  # âœ… Fix for missing cable config (reuses main DB)
  cable:
    url: <%= "#{ENV['DATABASE_URL']}?sslmode=require" %>
