default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paras_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: paras_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:root@localhost:5432/paras_production" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  sslmode: require

  cable:
    url: <%= ENV["DATABASE_URL"] %>
