default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paras_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: paras_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:root@localhost:5432/paras_production" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  sslmode: require

  # ðŸ‘‡ This ensures Action Cable (Solid Cable) uses the same DB as main app
  connects_to:
    database:
      writing: <%= ENV["DATABASE_URL"] %>
      reading: <%= ENV["DATABASE_URL"] %>

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
